######################################################################
# Automatically generated by qmake (1.07a) Sun Mar 25 11:20:39 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += GridUICanvas.h
SOURCES += GridUICanvas.cpp
